from . import hr_department
from . import hr_contract
from . import hr_employee
from . import hr_employee_transfert
from . import hr_setting
from . import hr_employee_desire
from . import hr_employee_lend
from . import hr_employee_assign
from . import hr_employee_task
from . import parser
